<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_length" value="0.05" />
    <xacro:property name="camera_width" value="0.1" />
    <xacro:property name="camera_height" value="0.05" />

    <xacro:property name="camera_fov_horizontal_deg" value="80" />
    <xacro:property name="camera_fov_vertical_deg" value="45" />

    <!-- Convert to radians -->
    <xacro:property name="camera_fov_horizontal_rad" value="${camera_fov_horizontal_deg * pi / 180.0}" />
    <xacro:property name="camera_aspect_ratio" value="${tan((camera_fov_vertical_deg * pi / 180.0) / 2.0) / tan((camera_fov_horizontal_deg * pi / 180.0) / 2.0)}" />
    <xacro:property name="camera_image_width" value="640" />
    <xacro:property name="camera_image_height" value="${round(camera_image_width * camera_aspect_ratio)}" />


    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
        </collision>
        <xacro:box_inertia m="0.1" x="${camera_length}" y="${camera_width}" z="${camera_height}"
                           o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${(base_length + camera_length) / 2.0 - base_length / 15.0} 0 ${base_height + camera_height / 2.0}" rpy="0 ${-20 * pi / 180.0} 0" />
    </joint>

    <link name="camera_link_optical" />

    <joint name="camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
    </joint>

    <gazebo reference="camera_link">
        <sensor name="camera" type="camera">
            <camera>
                <!-- <horizontal_fov>1.3962634</horizontal_fov> -->
                <horizontal_fov>${camera_fov_horizontal_rad}</horizontal_fov>
                <image>
                    <width>${camera_image_width}</width>
                    <height>${camera_image_height}</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>15</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
                <optical_frame_id>camera_link_optical</optical_frame_id>
                <camera_info_topic>camera/camera_info</camera_info_topic>
            </camera>
            <always_on>1</always_on>
            <update_rate>20</update_rate>
            <visualize>true</visualize>
            <topic>camera/image_raw</topic>            
        </sensor>
    </gazebo>

</robot>