<?xml version="1.0"?>
<robot name="lws"
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="2" />
    <xacro:property name="base_width" value="2" />
    <xacro:property name="base_height" value="0.5" />
    <xacro:property name="turret_base_radius" value="${base_width / 4}" />
    <xacro:property name="turret_base_length" value="${base_height / 1.75}" />
    <xacro:property name="turret_head_radius" value="${turret_base_radius / 8}" />
    <xacro:property name="turret_head_length" value="${1.5 * turret_base_radius}" />


    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="50.0" x="${base_length}" y="${base_width}" z="${base_height}" 
                           o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <link name="turret_base_link"> 
        <visual>
            <geometry>
                <cylinder radius="${turret_base_radius}" length="${turret_base_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="dark_gray" />
        </visual>
        <!-- <collision>
            <geometry>
                <cylinder radius="${turret_base_radius}" length="${turret_base_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision> -->
        <xacro:cylinder_inertia m="12.5" r="${turret_base_radius}" l="${turret_base_length}" 
                                    o_xyz="0 0 0" o_rpy="0 0 0" />

    </link>

    <joint name="base_turret_base_joint" type="revolute">
        <parent link="base_link"/>
        <child link="turret_base_link"/>
        <origin xyz="0 0 ${base_height + turret_base_length / 2.0}" rpy="0 0 ${- pi / 4.0}"/>
        <axis xyz="0 0 1"/>
        <limit 
            lower="${-40 * pi / 180.0}" 
            upper="${40 * pi / 180.0}" 
            effort="10.0" 
            velocity="1.0"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>
<!-- 
    <transmission name="base_turret_base_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_turret_base_joint">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="base_turret_base_motor">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission> -->


    <link name="turret_head_link"> 
        <visual>
            <geometry>
                <cylinder radius="${turret_head_radius}" length="${turret_head_length}"/>
            </geometry>
            <origin xyz="0 0 ${turret_head_length / 2.0}" rpy="0 0 0" />
            <material name="dark_gray" />
        </visual>
        <!-- <collision>
            <geometry>
                <cylinder radius="${turret_head_radius}" length="${turret_head_length}"/>
            </geometry>
            <origin xyz="0 0 ${turret_base_radius}" rpy="0 0 0" />
        </collision> -->
        <xacro:cylinder_inertia m="6.25" r="${turret_head_radius}" l="${turret_head_radius}" 
                                    o_xyz="0 0 0" o_rpy="0 0 0" />

    </link>

    <joint name="base_turret_head_joint" type="revolute">
        <parent link="turret_base_link"/>
        <child link="turret_head_link"/>
        <origin xyz="0 0 0" rpy="0 ${pi / 2.0} ${pi / 4.0}"/>
        <axis xyz="0 1 0"/>
        <limit 
            lower="${-45 * pi / 180.0}"
            upper="0" 
            effort="10.0" 
            velocity="1.0"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <!-- <transmission name="base_turret_head_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_turret_head_joint">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="base_turret_head_motor">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission> -->

</robot>
